# Generated by Django 3.2.7 on 2022-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tovaravet',
            field=models.BooleanField(default=False),
        ),
    ]
