# Generated by Django 3.2.7 on 2022-04-14 07:45

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bar_code', models.CharField(max_length=128, unique=True)),
                ('plu_code', models.PositiveIntegerField(default=product.models.random_number, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('litr', 'litr'), ('dona', 'dona')], default='dona', max_length=10)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('date_of_manufacture', models.DateField(blank=True, null=True)),
                ('discount', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
            ],
            options={
                'verbose_name_plural': 'Produktlar',
            },
        ),
        migrations.CreateModel(
            name='TrashProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('thrown_date', models.DateField(verbose_name='Chiqarib yuborilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Chiqarib Yuborilgan Produktlar',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name_plural': 'Sub Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='ReturnedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('sent_date', models.DateField(verbose_name='Yuborilgan sana')),
                ('is_returned', models.BooleanField(default=False)),
                ('received_date', models.DateField(verbose_name='Qabul qilingan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.supplier')),
            ],
            options={
                'verbose_name_plural': 'Qaytgan Produktlar',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.supplier'),
        ),
        migrations.CreateModel(
            name='MoveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('sent_date', models.DateTimeField(verbose_name='Jonatilgan sana')),
                ('is_received', models.BooleanField(default=False)),
                ('received_date', models.DateTimeField(verbose_name='Qabul qilingan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_market', to='market.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('to_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_market', to='market.market')),
            ],
            options={
                'verbose_name_plural': "Tovarllarni Ko'chirish",
            },
        ),
    ]
