# Generated by Django 3.2.7 on 2022-04-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveproduct',
            name='sent_date',
            field=models.DateField(verbose_name='Jonatilgan sana'),
        ),
    ]
