# Generated by Django 3.2.7 on 2022-04-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_moveproduct_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveproduct',
            name='received_date',
            field=models.DateField(verbose_name='Qabul qilingan sana'),
        ),
    ]
