# Generated by Django 3.2.7 on 2022-04-15 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_moveproduct_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_product', to='product.product'),
        ),
    ]
