# Generated by Django 3.2.7 on 2022-04-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220416_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedproduct',
            name='received_date',
        ),
    ]
